# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f746eb00db53597822292de92249ab76ca4e416c439619af30af68c5123205bb2760274807b2d17665b052b022d23431455915560bd11de2d0300b83fd892567

test:
  secret_key_base: ed8bb290cf4614d31a6e5494ec3f7f62018401f6ae75b74dc3d537fbb3afe6adc93ef9276a3ea671674813d6474a380598fa15c4c1ba0017022cfeb52d580bd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
